server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duberlyguarnizofuentesrivera/bootcamp-configurations.git
          clone-on-start: true
          skip-ssl-validation: true
  application:
    name: bootcamp-config-service
